---
# Source: hub/templates/rbac/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-agent-controller
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
  annotations:
---
# Source: hub/templates/rbac/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-agent-auth-server
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
  annotations:
---
# Source: hub/templates/admission-controller.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hub-agent-certs
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
data:
  cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUakNDQWphZ0F3SUJBZ0lRSGtndUxLLy9uK0Rtdm9QZTgxQVdtVEFOQmdrcWhraUc5dzBCQVFzRkFEQXIKTVNrd0p3WURWUVFERXlCb2RXSXRZV2RsYm5RdFkyOXVkSEp2Ykd4bGNpNWtaV1poZFd4MExuTjJZekFnRncweQpNVEE0TXpFeE5URXhNVFJhR0E4eU1USXhNRGt3TVRFMU1URXhORm93S3pFcE1DY0dBMVVFQXhNZ2FIVmlMV0ZuClpXNTBMV052Ym5SeWIyeHNaWEl1WkdWbVlYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDVUVvT2g2U0ZzcENTdmljalJERm94ZjQwZUJlUnlrN3h5ZTBxZ3hMa1ozSGpjVU5lRworS1A4N2N1bllaSEsva0krZllicC9pait6ay8xTFRtbVd1Y3BWaEVuaUswTktkU3RQTkxONkFZalZ6N1llbmxYClhWcXZmRUlpQVNKZFJnaTA4c0VrUzRoM2xHUjVaOTh2Y3c0cjh2RFhCR2hwanVLbUFJRUxtUi9YbitETTg2NW8KOXI0VUYxTG5EVzkzR05iSTJaRmJpUVRSWXNrSFY2by9UYkhSTXV4TzFONWJ0QjRkMTZBZC9jYTkzWG1KSWFFZwpHZFVMRlQrMWwvcEpOeWRER3N2ZjVsRkJHVDRFMTNXZ3BtNWtqdzhiNHVYL2t1TkpFNzhuQlZPbWNSRW5vcEc1Ci94SFRHaXkvTVptMHRJVldMaGJQNmxPRlowU1hMYjA5Zzk3VEFnTUJBQUdqYkRCcU1BNEdBMVVkRHdFQi93UUUKQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJdwpBREFyQmdOVkhSRUVKREFpZ2lCb2RXSXRZV2RsYm5RdFkyOXVkSEp2Ykd4bGNpNWtaV1poZFd4MExuTjJZekFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWVYVHhnT1J2eURXWGVLNzVIQUJhZVgvclB3NEk4SkovUS9HbURhT2sKNHI3dkxZb2VqUkFXNEZVSnN3bTY5VWFPZXZFV0hNRHRNV1h6MGlZbnFXMktCREQrVTNMUk1uakY4QmF2L3pkRApCL094L2lVQzJVeGNaT1BHeHZ1d2I0MHJabTRkTmR2OVNoYkJYWlFGMEpWSDFNRzFKUjVwaGVhWnJKV25qcDJzCjZQTlVkRUlhTXYwUWcwOUZVcWhVbGgwQ2V4UDdhdGkvQUpqcVYvakNsa0ozUXFUYkRvQkl1bldPcnd3azBqd2oKa2FuVy85bkl0eTBIWlczK2UwT2orM0ZKNG5uRDJHL0lIRk8xc3hWMTF3ZGFGS1RybDQ0SmVmZTRmeVcvd0FZTAprZHhvaFFyanRsd2xaaWhtWUxRbndTMFQ0QkF4Q0djVVMyRy9uVjVMdXZLVXhRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbEJLRG9la2hiS1FrcjRuSTBReGFNWCtOSGdYa2NwTzhjbnRLb01TNUdkeDQzRkRYCmh2aWovTzNMcDJHUnl2NUNQbjJHNmY0by9zNVA5UzA1cGxybktWWVJKNGl0RFNuVXJUelN6ZWdHSTFjKzJIcDUKVjExYXIzeENJZ0VpWFVZSXRQTEJKRXVJZDVSa2VXZmZMM01PSy9MdzF3Um9hWTdpcGdDQkM1a2YxNS9nelBPdQphUGErRkJkUzV3MXZkeGpXeU5tUlc0a0UwV0xKQjFlcVAwMngwVExzVHRUZVc3UWVIZGVnSGYzR3ZkMTVpU0doCklCblZDeFUvdFpmNlNUY25ReHJMMytaUlFSaytCTmQxb0tadVpJOFBHK0xsLzVMalNSTy9Kd1ZUcG5FUko2S1IKdWY4UjB4b3N2ekdadExTRlZpNFd6K3BUaFdkRWx5MjlQWVBlMHdJREFRQUJBb0lCQUhZWTVoL0d2ci9Wa3VUbQpjZUk1aGQ0Z3F6NmMySDJCMHpWRG5GdnBTdkNUWlZuaXFHT2YvN3NGTmY3RDFQSWdKRm1PNklITUVvcFhwbklYCnBmbEdXMFFldndQWEFKNlZGR2t2TDdyR0tjOGFFS2U3MXZlVkgzVURHQVBpLzdPQTNnVGo4S093RXFHOUd2MngKbU5KUlk2WXQxMlRHd1RnZm5DbG1FWVpjbEliMmFGU090WVBvWS95L09zWExUS1dDa1VhTmVQcEpLdks4dzExRgpLSGpvMzhyUDdTbG9URmszYUM0N0NLWDBsYnZtZ0ZveFBDL3U3SVV4eFBRZUhrS2tUbG9SOXhEYWJ0OThyZVMvCnc2U2wzNU9sMlVoOVg5dHNxM3lNbGtjUUVRRVJ0TWxpZHVyVzl6TzZncVBEbE5YYjZiYkI5eXhSUGQ5QWJocHkKSHphUWRSRUNnWUVBdzVhNWF1TEFGNlJiU3d0T0tudlBpZkhGRTRiWWppTGRxZjFZbitadW11V05GNGtMNjM0eAo1djU3c05rcUxPaVBiL2JLR0hxWU0rclJyeG5HVXI0MUFhQ2ZldFFzUUhQUVZVS09RNnRUQ1VkNGpEMU9OT2QwClUvcDVjYVVwY1I3STQ4MXNWWXVVUHpjZVM4dVBINmUzbVpyYXJRWDFIVWtGWFZTV0x5Wk5xZWNDZ1lFQXdjNmwKcGpMME5ZeklDRVBJV1BoRjhrSHhhcmlzanh5VTBwWXNsSHJreVhYNmNXbVRIKytRQlJTQ2dST2w3VTVzS0J3bgphRnNCK1pPek5mNHltTDBVUTNDZlFuN3NBMTk0MGk3KzZsOU5yR1YxV0QwYUtTYTJOMExQRU9MS25ZNUJaOWd6CjNQYjA5eXYzWVlENFNsY3hoZzJscFNNZlZLaGF2d1JLOTZHd2ZqVUNnWUVBcmxvTS9ZZ1dmcnpIbVBVQ0FBTVEKZGNKczBNUlRCUmwxaWRSS2pYZkh2eExFSEdmUmxXS1FMMzlKV2RPc3NnMjUxN0FpWllIYmJlUjBlT2U4RUFSNAprZlBTVnBjT3Y0RytCRkxwS005dm5RVDJJK1YrY3RDa3RUdkJ5Sm5YZ0h4VnppUlAzMDRtbjllTmpUbHZZMk9KCjJrYmRpb0dXQ0Q0UXB5c0JHaFRHQko4Q2dZRUFsUC9iaUtBcDhqV080QlBFcHVvUlZJUHdKOTFkQlJXek1RZTEKdEYyYklXdXJwSi9ITmNsSER6REtlSlB6Z0ROSG9icXJiV1p5YVQ5dGl6Z29EQmRweWNOL0hXOVk0ZXIzaDVnTAo4WUpkeEFtb29yTXZOcTRGYnd6VkJ5VmxJcVpva0g2K3VNWEFaWHNPMEk2SDFSZWVBbkxoZzhreDRETWl1VEtDCnRFbEIySFVDZ1lBSlJwVnQ3QmxvQXJGSS9WV0QxRWV6S3FlV0g3YWVyM1RwVnpxdHNPUkoxSmNTYUtWZ3JtQXgKMEgvdWVWaE9rcWJibmhxSFFOb2JqczhwQjNRMWlIT0QwWm1LQk9yRVVlQVVzcmxQeVRqWFBNVzlJdDNucmRncwpIak90TFAvcklZcUt0NTBYRjdBU01lUU5IdC9lVlQzVUV2dHBCQ28xYXZkMHo0WWcrR2ZqaFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
---
# Source: hub/templates/rbac/cluster-role-auth-server.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-agent-auth-server
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
rules:
  # Access Control RBACs.
  - resources:
      - accesscontrolpolicies
    apiGroups:
      - hub.traefik.io
    verbs:
      - list
      - watch
---
# Source: hub/templates/rbac/cluster-role-controller.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-agent-controller
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
rules:
  # Access Control RBACs.
  - apiGroups:
      - networking.k8s.io
      - hub.traefik.io
    resources:
      - ingressclasses
    verbs:
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - update
  - apiGroups:
      - hub.traefik.io
    resources:
      - accesscontrolpolicies
    verbs:
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
    verbs:
      - create
      - get
      - update
      - delete
  # Other RBACs.
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
# Source: hub/templates/rbac/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hub-controller
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-agent-controller
subjects:
  - kind: ServiceAccount
    name: hub-agent-controller
    namespace: default
---
# Source: hub/templates/rbac/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hub-auth-server
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-agent-auth-server
subjects:
  - kind: ServiceAccount
    name: hub-agent-auth-server
    namespace: default
---
# Source: hub/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: hub-agent-controller
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
  annotations:
    hub.traefik.io/ingress-controller: none
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: hub-agent-webhook
  selector:
    app: hub-agent
    component: controller
---
# Source: hub/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: hub-agent-auth-server
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
  annotations:
    hub.traefik.io/ingress-controller: none
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: hub-agent-auth
  selector:
    app: hub-agent
    component: auth-server
---
# Source: hub/templates/deployment-auth-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-agent-auth-server
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
  annotations:
    hub.traefik.io/ingress-controller: none
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hub-agent
      component: auth-server
  template:
    metadata:
      labels:
        app: hub-agent
        component: auth-server
      annotations:
    spec:
      serviceAccountName: hub-agent-auth-server
      containers:
        - name: hub-agent-auth-server
          env:
            - name: DISABLE_GIT_SSL_VERIFY
              value: "true"
          image: "ghcr.io/traefik/hub-agent:latest"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /_ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /_live
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
          args:
            - auth-server
            - --listen-addr=:80
            - "--log-level=debug"
---
# Source: hub/templates/deployment-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-agent-controller
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
  annotations:
    hub.traefik.io/ingress-controller: none
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-agent
      component: controller
  template:
    metadata:
      labels:
        app: hub-agent
        component: controller
      annotations:
    spec:
      serviceAccountName: hub-agent-controller
      containers:
        - name: hub-agent-controller
          env:
            - name: DISABLE_GIT_SSL_VERIFY
              value: "true"
          image: "ghcr.io/traefik/hub-agent:latest"
          imagePullPolicy: Always
          resources:
          volumeMounts:
            - mountPath: /var/run/hub-agent/
              name: hub-certs
          args:
            - controller
            - --token=plop
            - --acp-server.listen-addr=:443
            - --acp-server.cert=/var/run/hub-agent/cert.pem
            - --acp-server.key=/var/run/hub-agent/key.pem
            - --acp-server.auth-server-addr=http://hub-agent-auth-server.default.svc.cluster.local
            - "--log-level=debug"
      volumes:
        - name: hub-certs
          secret:
            secretName: hub-agent-certs
            items:
              - key: cert
                path: cert.pem
              - key: key
                path: key.pem
---
# Source: hub/templates/admission-controller.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hub
  namespace: default
  labels:
    app.kubernetes.io/name: hub
    helm.sh/chart: hub-0.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.7.0
    app.kubernetes.io/instance: hub
webhooks:
  - name: hub-agent.default.svc
    clientConfig:
      service:
        name: hub-agent-controller
        namespace: default
        path: /
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUakNDQWphZ0F3SUJBZ0lRSGtndUxLLy9uK0Rtdm9QZTgxQVdtVEFOQmdrcWhraUc5dzBCQVFzRkFEQXIKTVNrd0p3WURWUVFERXlCb2RXSXRZV2RsYm5RdFkyOXVkSEp2Ykd4bGNpNWtaV1poZFd4MExuTjJZekFnRncweQpNVEE0TXpFeE5URXhNVFJhR0E4eU1USXhNRGt3TVRFMU1URXhORm93S3pFcE1DY0dBMVVFQXhNZ2FIVmlMV0ZuClpXNTBMV052Ym5SeWIyeHNaWEl1WkdWbVlYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDVUVvT2g2U0ZzcENTdmljalJERm94ZjQwZUJlUnlrN3h5ZTBxZ3hMa1ozSGpjVU5lRworS1A4N2N1bllaSEsva0krZllicC9pait6ay8xTFRtbVd1Y3BWaEVuaUswTktkU3RQTkxONkFZalZ6N1llbmxYClhWcXZmRUlpQVNKZFJnaTA4c0VrUzRoM2xHUjVaOTh2Y3c0cjh2RFhCR2hwanVLbUFJRUxtUi9YbitETTg2NW8KOXI0VUYxTG5EVzkzR05iSTJaRmJpUVRSWXNrSFY2by9UYkhSTXV4TzFONWJ0QjRkMTZBZC9jYTkzWG1KSWFFZwpHZFVMRlQrMWwvcEpOeWRER3N2ZjVsRkJHVDRFMTNXZ3BtNWtqdzhiNHVYL2t1TkpFNzhuQlZPbWNSRW5vcEc1Ci94SFRHaXkvTVptMHRJVldMaGJQNmxPRlowU1hMYjA5Zzk3VEFnTUJBQUdqYkRCcU1BNEdBMVVkRHdFQi93UUUKQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJdwpBREFyQmdOVkhSRUVKREFpZ2lCb2RXSXRZV2RsYm5RdFkyOXVkSEp2Ykd4bGNpNWtaV1poZFd4MExuTjJZekFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWVYVHhnT1J2eURXWGVLNzVIQUJhZVgvclB3NEk4SkovUS9HbURhT2sKNHI3dkxZb2VqUkFXNEZVSnN3bTY5VWFPZXZFV0hNRHRNV1h6MGlZbnFXMktCREQrVTNMUk1uakY4QmF2L3pkRApCL094L2lVQzJVeGNaT1BHeHZ1d2I0MHJabTRkTmR2OVNoYkJYWlFGMEpWSDFNRzFKUjVwaGVhWnJKV25qcDJzCjZQTlVkRUlhTXYwUWcwOUZVcWhVbGgwQ2V4UDdhdGkvQUpqcVYvakNsa0ozUXFUYkRvQkl1bldPcnd3azBqd2oKa2FuVy85bkl0eTBIWlczK2UwT2orM0ZKNG5uRDJHL0lIRk8xc3hWMTF3ZGFGS1RybDQ0SmVmZTRmeVcvd0FZTAprZHhvaFFyanRsd2xaaWhtWUxRbndTMFQ0QkF4Q0djVVMyRy9uVjVMdXZLVXhRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    sideEffects: None
    admissionReviewVersions: [ "v1" ]
    rules:
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: [ "extensions" ]
        apiVersions: [ "v1beta1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: [ "networking.k8s.io" ]
        apiVersions: [ "v1beta1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: [ "networking.k8s.io" ]
        apiVersions: [ "v1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: [ "traefik.containo.us" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "ingressroutes" ]
        scope: "Namespaced"
